mounts:
  - source: './content'
    target: 'content'
  - source: './static'
    target: 'static'
  - source: './src/layouts'
    target: 'layouts'
  - source: './data'
    target: 'data'
  - source: './src/assets'
    target: 'assets'
  - source: './content/i18n'
    target: 'i18n'
  - source: './src/types'
    target: 'archetypes'
