# Theme configuration
BookTheme: 'auto'
BookSection: '*'
BookRepo: 'https://github.com/lucendio/lecture-devops-infos'
BookDateFormat: '2006-01-02'
BookSearch: true
BookComments: false
BookServiceWorker: false

timeZone: 'Europe/Berlin'
